permalink: /posts/:title.html
pygments: true
markdown: rdiscount

domain: sceditor.samclarke.com
title: SCEditor
author: Sam Clarke
email: sam@samclarke.com

disqus:
  id: sceditor

github:
  username: samclarke
